### PR TITLE
Make pgcrypto rails 4 compatible by default

### PR DESCRIPTION
**Pull request by mhenrixon**
Not sure if anything else is needed or you want to check if attr_protected is installed and then generate attr_accessible if it is. 

Just thought I should get a discussion going. So please do tell if you feel like this could be done better. I have one question for you though I seem to be missing a key in my specs. I'd prefer if we could have that key available in the repo as well so that nothing is needed to make the tests run properly.

I'm unsure if my changes breaks any existing functionality though.

### CODE REVIEW

**Comment by tadd** [comment]
:+1: for this.

I have motivation to use `pgcrypto` with Rails4 and I found this.
I've never tested this well, but this is enough simple and good to start Rails4 support, so I hope this is merged.

**Comment by MattNewberry** [comment]
@mhenrixon have you removed your fork of this?

**Comment by flipsasser** [comment]
Hey guys, I totally didn't see this until just now. Will merge and push shortly!

**Comment by jmcbri** [comment]
Thanks Flip!  Really looking forward to it.

**Comment by jmcbri** [comment]
So how's it going Flip? I'm so going to FLIP when you address this ; )  !!

**Comment by flipsasser** [comment]
It's going well. I've refactored the tests to test two versions of ActiveRecord (backwards compatibility and what-have-you). Once I've gotten them both ironed out, I'll merge the pull request manually, since I'm conducting that refactor on your branch.

**Comment by flipsasser** [comment]
Also, NICE ;)

**Comment by jmcbri** [comment]
Thanks Phil!  (Though I don't know why you're doing it on my branch, hope I
haven't screwed up that branch.  BTW, don't know what you mean when you say
NICE ; , but I hope it's a good thing, email tends to be a poor medium for
some things.)

**Comment by flipsasser** [comment]
I was saying "NICE" to the "Flip" jokes. I thoroughly enjoyed them.

And I'm doing it on your branch to account for Rails 4!

**Comment by jmcbri** [comment]
Thanks!

I'll tell you, what you've done is incredibly impressive and most
appreciated.

**Comment by jmcbri** [comment]
By the way, is the anything I need to do to the branch to make it possible
for you to do what you need to do?  (I'm a noob, as you know.)

Separately, is there anything can do that would help you but that doesn't
require your level expertise.

**Pull request closed without merging**
